### ISSUE TITLE
How to specify version?

### ISSUE THREAD

**Issue by tim-3bc7s8** [kemra102/puppet-zabbix#12]
This may be due to my lack of knowledge about how to configure puppet, but I am not sure how to specify the zabbix version.

I have this in my templates.pp file:

    class monitored {
        class { '::zabbix::client':
                server => '10.128.7.123',
                serveractive => '10.128.7.123',
        }
    }

I want to add a specific version to it:

    class monitored {
        class { '::zabbix::client':
                server => '10.128.7.123',
                serveractive => '10.128.7.123',
               version => '2.4',
        }
    }

But that doesn't seem to work.

I get this on the client:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter version on Class[Zabbix]

**Comment by kemra102** [comment]
The docs are particularly bad in this area. Currently you can only set the version via the '::zabbix::repo' class:

```puppet
class monitored {
    class { '::zabbix::client':
            server => '10.128.7.123',
            serveractive => '10.128.7.123',
    }
    class { '::zabbix::repo':
            version => '2.4',
    }
}
```

The above should work fine but I'll certainly be working on giving better ways to set the version and updating the docs to reflect this.

Based on your previous posts you were using SL6 which should default to Zabbix 2.4 anyway. If you have older SL versions in use please be aware that Zabbix SIA do not necessarily support the newer Zabbix versions on your OS.

**Comment by tim-3bc7s8** [comment]
I am wanting to use this in an attempt to prevent any unintended client upgrades in the future. Not even sure if that would happen in this case. To be honest, I'm fairly new to puppet and this is the first module I'm putting effort into deploying.

Either way, I tried your example and now it is displaying this error:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Duplicate declaration: Class[Zabbix::Repo] is already declared; cannot redeclare

**Comment by kemra102** [comment]
That's a fair reason to specify the version.

All my testing takes place on boxes that use Hiera to change these values so it works for me. Setting the variable however in a custom module like you are doing (certainly like I did when I first used Puppet) fails due to the way catalogues are compiled and the difference between calling a class directly and using an include (if you're at all interested on the issues at play Gary Larizza's blog [here](http://garylarizza.com/blog/2014/02/17/puppet-workflow-part-2/) explains this in more detail in the section called "Use parameterized class declarations and explicitly pass values you care about").

I'll look at re-writing things tonight to make this custom class friendly as well as fully supporting Hiera as it currently does. It should be a small change either way.

**Comment by kemra102** [comment]
Just an update. Gary's post reminded me that this is possible with the way the module is currently written, order is important:

```puppet
class { '::zabbix::repo':
  version => '2.2',
}
class { '::zabbix::client':
  server          => '10.128.7.123',
  serveractive => '10.128.7.123',
}
```
Code & doc changes are coming but if you need something in the mean time this should do.

**Comment by tim-3bc7s8** [comment]
Changing the order worked without any errors.  Thanks.

**Comment by kemra102** [comment]
New version has also been released to Puppet forge with improved version support and documentation for it.
